spring:
  mail:
    host: smtp.163.com
    username: 15221570989@163.com
    password: 199522cyt
    port: 25
    protocol: smtp
    default-encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://152.136.24.197:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yuting
    password: 199522cytCYT@
